---
title: "Draft Quarto document"
author: "Your Name"
format: html
---


## Header 1

```{r setup}
library(tidyverse)
library(here)
library(fs)
library(snakecase)
source(here("R/functions.R"))
```

## Importing new data

```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5c/5c_1586886626/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE, # fjerner boks med information
    name_repair = to_snake_case, # convert til snaketekst med__
    n_max = 100 # maks antal numbers
  )
```

## exercise, reading other files
```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5c/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```


```{r}
#| eval: false
here("data-raw/nurses-stress/stress/6b/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Creating a function
```{r}
#' Add two numbers together
#'
#' @param num1 A number here
#' @param num2 A number here
#'
#' @returns Returns the sum of two numbers
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```


```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read()
```

```{r}
#| eval: false
# Outputs only 100 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()

# Outputs only 1000 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = 1000)

# Outputs all rows (`Inf` means infinity)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = Inf)
```

## Day 2, using map
```{r}
hr_files <- here("data-raw/nurses-stress/") %>%
  dir_ls(regexp = "HR.csv.gz", recurse = TRUE)

hr_data <- hr_files %>%
  map(read) %>% # no brackets here!
  list_rbind(names_to = "file_path_id")

hr_data
```

## Exercise: Convert map to function and use on sleep

```{r}
hr_data <- read_all("HR.csv.gz")
ibi_data <- read_all("IBI.csv.gz")
bvp_data <- read_all("BVP.csv.gz")
```

## Inspecting the data

```{r}
hr_data <- read_all("HR.csv.gz")

survey_data <- here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read()

hr_data
survey_data
```

```{r}
hr_data %>%
  mutate(
    id = str_extract(
      file_path_id,
      pattern = "/stress/[:alnum:]{2}/"
    ) %>%
      str_remove("/stress/") %>%
      str_remove("/"),
    .before = file_path_id
  ) %>%
  select(-file_path_id)
```

```{r}
```
